# Generated by Django 5.1.6 on 2025-03-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('cve_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'motivos',
                'managed': False,
            },
        ),
    ]
