# Generated by Django 5.1.6 on 2025-03-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('cve_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especies/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'especies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('cve_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('sexo', models.BooleanField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especies/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Razas',
            fields=[
                ('cve_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='razas/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'razas',
                'managed': False,
            },
        ),
    ]
