# Generated by Django 5.1.6 on 2025-03-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_municipios_delete_ciudades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('cve_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'trabajadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('cve_turno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinarios',
            fields=[
                ('cve_veterinarios', models.AutoField(db_column='cve_veterinarios', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'veterinarios',
                'managed': False,
            },
        ),
    ]
